### ISSUE TITLE
External Room - Cannot leave room when no admin and no moderator are in the room

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/synapse-manage-last-admin#11]
### Scenarios
- **Scenario 4 - Salon Externe - Pas de moderateur = >KO** 
6 Participants : 1 admin - 3 par defaut - 2 externe
Admin quitte le salon => il peut pas quitter erreur 
![image](https://github.com/tchapgouv/tchap-infra/assets/3725676/73975948-32c5-4f3e-abb8-6ee4fa0bd205) 

- **Scenario 6 - Salon Externe - Quitter le salon => KO**
  - Je cree un salon externe
  - Je quitte le salon externe => il peut pas quitter - erreur
  ![image](https://github.com/tchapgouv/tchap-infra/assets/3725676/73975948-32c5-4f3e-abb8-6ee4fa0bd205) 
  
  
 ### Test to perform to valide this issue
 - Scenario 1 - Salon Privee - Pas de moderateur
3 Participants : 1 admin - 2 par defaut
Admin quitte le salon 
=> resultat attendu : les 2 par default deviennent admin 
Note : tous les invites seront admin 

- Scenario 2 - Salon Privee - Pas de moderateur - Multi Admin 
3 Participants : 2 admin - 1 par defaut
1 Admin quitte le salon 
=> resultat attendu : 1 admin doit rester admin, 1 par defaut doit rester par defaut
Note : tous les invites seront admin 

- Scenario 3 - Salon Privee - Moderateur
3 Participants : 1 admin - 1 moderateur - 1 par defaut
Admin quitte le salon 
=> resultat attendu : 1 moderateur doit devenir admin

- Scenario 4 - Salon Externe - Pas de moderateur
6 Participants : 1 admin - 3 par defaut - 2 externe
Admin quitte le salon 
=> resultat attendu : les 3 par default doivent devenir admin , les 2 externes doivent rester pareil

- Scenario 5 - Salon Externe - Moderateur
6 Participants : 1 admin - 2 moderateurs - 1 par defaut - 2 externe
Admin quitte le salon 
=> resultat attendu : 2 moderateurs doivent devenir admin

- Scenario 6 - Salon Externe - Quitter le salon
  - Je cree un salon externe
  - Je quitte le salon externe (personne n'est dans le salon)
=> resultat attendu : on peut quitter le salon sans erreur

**Comment by jdauphant** [comment]
j'ai du mal à comprendre "resultat attendu" c'est ce qui est obtenu dans les tests ou il n'y a que les scénarios 4 et 6 qui ont été testé ?

**Comment by jdauphant** [comment]
pour le scénario 6 il n'y a personne dedans ?

**Comment by mcalinghee** [comment]
> j'ai du mal à comprendre "resultat attendu" c'est ce qui est obtenu dans les tests ou il n'y a que les scénarios 4 et 6 qui ont été testé ?

- resultat attendu est le resultat auquel on s'attend quand on fera les tests (pas ce qui a ete obtenu)
- les tests ont ete listes ici car il faudra tester tous ces scenarios pour eviter les regressions
- scenario 6 : effectivement personne dedans
- scenario 4 et 6 sont les scenarios pour reproduire le probleme de cette issue

**Comment by mcalinghee** [comment]
**Cause du probleme** 
La cause du probleme est due au fait que l'on ne peut pas changer les permissions au niveau d'une room pour mettre tous les users en admin : 
voir le module [synapse-room-access-rules](https://github.com/vector-im/synapse-room-access-rules/blame/08e019173909b9c14c0bd92a0af8e49e858f4ae3/room_access_rules/__init__.py#L669) qui rentre en conflit avec ce module last-admin.

**Comment by mcalinghee** [comment]
Historique de https://github.com/tchapgouv/tchap-infra/pull/2218
<img width="771" alt="image" src="https://github.com/tchapgouv/synapse-manage-last-admin/assets/3725676/0644b589-47a2-45c5-af00-023c13af6ecb">
<img width="733" alt="image" src="https://github.com/tchapgouv/synapse-manage-last-admin/assets/3725676/7f2517c8-bf37-42ea-b545-15ea8893137b">
<img width="745" alt="image" src="https://github.com/tchapgouv/synapse-manage-last-admin/assets/3725676/4a9b372c-39f1-4e98-b9d4-7a4305399956">
<img width="800" alt="image" src="https://github.com/tchapgouv/synapse-manage-last-admin/assets/3725676/85956891-7597-45ca-bc61-b085a23ebac2">
<img width="753" alt="image" src="https://github.com/tchapgouv/synapse-manage-last-admin/assets/3725676/d9f178b1-bd97-4a3e-9d6f-9f73688e5d06">

**Comment by mcalinghee** [comment]
### Solution 5
- si il y a des moderateurs, on promeut les modérateurs en admin comme actuellement
- si pas de modérateurs, on promeut 10 membres non-externes du salon (au lieu de changer les permissions du salon)

Avantages :
- on peut gerer les salons externes 
- pas de modification sur les autres modules

Désavantages :
- tout le monde n'est pas d'admin et donc il se peut que les 10 admins ne soient pas forcément réactifs pour remettre le salon dans un état normal


cc @tchapgouv/bizdev @odelcroi @jdauphant

**Comment by jdauphant** [comment]
> ### Solution 5
> - si il y a des moderateurs, on promeut les modérateurs en admin comme actuellement
> - si pas de modérateurs, on promeut 10 membres non-externes du salon (au lieu de changer les permissions du salon)
> 
> Avantages :
> - on peut gerer les salons externes 
> - pas de modification sur les autres modules
> 
> Désavantages :
> - tout le monde n'est pas d'admin et donc il se peut que les 10 admins ne soient pas forcément réactifs pour remettre le salon dans un état normal
> 
> 
> cc @tchapgouv/bizdev @odelcroi @jdauphant 

Les admins sont irrévocable alors que changer  les permissions par défaut permet de se mettre admin et ensuite de révoquer la situation d'admin par défaut.
